Baseball/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


from users import views as user_views
from django.contrib.auth import views as auth_views



import KBA.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('KBA/', include('KBA.urls')),
    path('', RedirectView.as_view(url='KBA/')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

KBA/urls.py
# KBA/urls.py

from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('teams/', views.teams, name='team-list'),
    path('teams/<str:name>/', views.team_detail, name='team-detail'),
    path('players', views.AllPlayerList.as_view(), name='player-list'),
    path('players/<str:uuid>/', views.player_detail, name='player-detail'),
    path('schedule/', views.AllMatchList.as_view(), name ='match-list'),
    path('blog/', views.AllBlogList.as_view(), name='blog-index'),
    path('blog/<int:pk>', views.BlogDetailView.as_view(), name='blog-detail'),
    path('blog/new', views.BlogCreateView.as_view(), name='blog-create'),
    path('blog/<int:pk>/update', views.BlogUpdateView.as_view(), name='blog-update'),
    path('blog/<int:pk>/delete', views.BlogCreateView.as_view(), name='blog-delete'),
    path('blog/<int:pk>/comment', views.BlogCreateView.as_view(), name='blog-form-comment'),



]

KBA/models.py
import uuid

from django.db import models
from django.utils import timezone
import datetime
from multiselectfield import MultiSelectField
from django.urls import reverse
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User



# Team history/roster/stats reamin even when it's deleted from ...


# class Roster(models.Model):
#     team = models.ForeignKey(Team, on_delete=models.CASCADE)
#     players = 'Player'
#     updated = models.DateTimeField(default=timezone.now())
#
#     def __str__(self):
#         return self.team

class Player(models.Model):
    PRIMARY_CHOICES = [
        ('Right', 'Right'),
        ('Left', 'Left'),
        ('Both', 'Both')]

    POSITION_CHOICES = [
        ('Pitcher', (
            ('P', 'Pitcher'),
            ('SP', 'Starting Pitcher'),
            ('RP', 'Relief Pitcher'),
        )
         ),
        ('Catcher', (
            ('C', 'Catcher'),
        )
         ),
        ('Infielder', (
            ('IF', 'Infield'),
            ('1B', 'First Base'),
            ('2B', 'Second Base'),
            ('3B', 'Third Base'),
            ('SS', 'Shortstop'),
        )
         ),
        ('Outfielder', (
            ('OF', 'Outfield'),
            ('LF', 'Left Field'),
            ('RF', 'Right Field'),
            ('CF', 'Center Field'),
        )
         ),
        ('Utility', (
            ('Util', 'Utility'),
        )
         ),
    ]

    EXPERIENCE_CHOICES = [
        ('HS', 'High School'),
        ('COLL', 'College'),
        ('D1', 'Division 1'),
        ('INDY', 'Independent League'),
        ('MILB', 'Minor League'),
        ('MLB', 'Major League'),
        ('PRO', 'Other Professional League')
    ]

    YEAR_CHOICES = []

    uuid = models.UUIDField('UUID', primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=50)
    team = models.ManyToManyField('Team', through='PlayerToTeam', related_name='player')
    primary_position = models.CharField(max_length=30, choices=POSITION_CHOICES, default=POSITION_CHOICES[4][0][0])
    other_position= MultiSelectField(choices=POSITION_CHOICES, null=True, blank=True)
    bats = models.CharField(max_length=10, choices=PRIMARY_CHOICES)
    throws = models.CharField(max_length=10, choices=PRIMARY_CHOICES)
    DOB = models.DateField()

    for r in range(2000, (datetime.datetime.now().year)):
        YEAR_CHOICES.append((r,r))
    dateJoined = models.IntegerField('Year Joined', choices=YEAR_CHOICES, default=datetime.datetime.now().year)
    experience = models.CharField(max_length=30, choices=EXPERIENCE_CHOICES, null=True, blank=True)
    updated = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('player-detail', kwargs={'uuid': self.uuid})


class Team(models.Model):
    name = models.CharField(max_length=20)
    year_formed = models.IntegerField()
    manager = models.CharField(max_length=20)
    players = models.ManyToManyField(Player, through='PlayerToTeam', related_name='teams') ## how do I use related_name for reverse relationship?
    content = models.TextField()
    no_titles = models.IntegerField(help_text="Number of Championship Title")
    updated = models.DateTimeField(default=timezone.now)
    # picture = models.ImageField(upload_to='images/team_pics')

    def __str__(self):
        return self.name

class PlayerToTeam(models.Model):
    team = models.ForeignKey(Team, null= True, on_delete=models.SET_NULL)
    players = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL)
    back_number = models.IntegerField(unique=True)
    current_team = models.BooleanField(default=False)
    manager = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.players} to {self.team}'

class Field(models.Model):
    name = models.CharField(max_length=40)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

class Season(models.Model):
    year = models.IntegerField()

    def __str__(self):
        return self.year


class Match(models.Model):
    season = models.ForeignKey(Season, null=True, on_delete=models.SET_NULL, related_name='season_matches')
    slug = models.SlugField(null=True, blank=True, unique=True)
    home_team = models.ForeignKey(Team, null=True, on_delete=models.SET_NULL, related_name='home_matches')
    away_team = models.ForeignKey(Team, null=True, on_delete=models.SET_NULL, related_name='away_matches')
    field = models.ForeignKey(Field, on_delete=models.CASCADE)
    date = models.DateTimeField()

    def __str__(self):
        return f'{self.away_team} at {self.home_team}'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f'{self.away_team} vs. {self.home_team}')
        return super().save(*args, **kwargs)

class BoxScore(models.Model):
    match = models.OneToOneField(Match, on_delete=models.CASCADE)
    run_hometeam = models.IntegerField()
    run_awayteam = models.IntegerField()
    hits_hometeam = models.IntegerField()
    hits_awayteam = models.IntegerField()
    error_hometeam = models.IntegerField()
    error_awayteam = models.IntegerField()


    def win(self):
        if self.run_hometeam > self.run_awayteam:
            hometeam_win = 1
            return hometeam_win
        elif self.run_awayteam > self.run_hometeam:
            awayteam_win = 1
            return awayteam_win
        else:
            hometeam_draw = 1
            awayteam_draw = 1
            return hometeam_draw, awayteam_draw

    def __str__(self):
        return self.match

class Standing(models.Model):
    team = models.ForeignKey(Team, on_delete=models.SET_NULL, null=True)


class MatchStats(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='stats')
    PA = models.IntegerField()
    R = models.IntegerField()
    H = models.IntegerField()
    double = models.IntegerField()
    triple = models.IntegerField()
    HR = models.IntegerField()
    RBI = models.IntegerField()
    BB = models.IntegerField()
    SO = models.IntegerField()
    GDP = models.IntegerField()
    HBP = models.IntegerField()
    SF = models.IntegerField()
    sac_bunt = models.IntegerField()

    @property
    def AB(self):
        # PA - (BB + HBP + SF + sac_bunt)
        return self.AB - (self.BB + self.HBP + self.SF + self.sac_bunt)

    def __str__(self):
        return self.match

    # players = models.ManyToManyField(Player, related_name='games')

class PositionStats(models.Model):
    season = models.ForeignKey(Season, null=True, on_delete=models.SET_NULL)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    MatchStats = models.ForeignKey(MatchStats, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.player

class Blog(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    updated = models.DateTimeField(default=timezone.now)
    blog_user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog-detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    comment_title = models.CharField(max_length=200)
    comment_text = models.TextField()
    comment_updated = models.DateTimeField(default=timezone.now)
    comment_user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.comment_title







# player history shows previous teams / stats
# 블로그
# 선수 스탯,
# 경기 스케쥴
# 경기 결과
# 메인페이지에 지역 비지니스 스폰서 광고
# about 페이지 + 구글 지도
# 로그인 관리





# Stats

# class StatsBase(models.Model):
#     class Meta:
#         abstract = True
#
#     PA = models.IntegerField()
#     AB =

KBA/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class meta:
        model = Comment
        fields = ['comment_title', 'comment_text']

KBA/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404

from django.views.generic import ListView, DetailView, CreateView, UpdateView, FormView
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import FormMixin, DeleteView

from django.contrib.auth.mixins import LoginRequiredMixin

from KBA.forms import CommentForm
from .models import Team, Player, PlayerToTeam, Blog, Match


# def index(request):
#    # teams = Team.objects.all()
#    # context = {'teams': teams}
#    # return render(request, 'index.html', context)
#    try:
#        teams = Team.objects.all()
#    except Team.DoesNotExist:
#        raise Http404("Team does not exist")
#    return render(request, 'index.html', {'teams': teams})

def index(request):
    teams = Team.objects.all()
    context = {'teams': teams}
    return render(request, 'index.html', context)


def about(request):
    return render(request, 'KBA/about.html')


def teams(request):
    try:
        teams = Team.objects.all()
    except Team.DoesNotExist:
        raise Http404("Team does not exist")
    return render(request, 'KBA/teams.html', {'teams': teams})


def team_detail(request, name):
    team = Team.objects.get(name=name)
    players = team.players.all()

    context = {'team': team,
               'players': players

               }
    return render(request, 'KBA/team_detail.html', context)


class AllPlayerList(ListView):
    model = Player


def player_detail(request, uuid):
    player = Player.objects.get(uuid=uuid)
    team = Team.objects.all()

    context = {'player': player,
               'team': team
               }
    return render(request, 'KBA/player_detail.html', context)


class AllMatchList(ListView):
    model = Match



# Blog0

class AllBlogList(ListView):
    model = Blog


class BlogDetailView(DetailView):
    model = Blog



class BlogCreateView(CreateView):
    model = Blog
    field = ['title', 'content']
    template_name = 'KBA/blog_create_form.html'

    def form_valid(self, form):
        form.instance_blog_user = self.request.user
        return super().form_valid(form)

class BlogUpdateView(UpdateView):
    model = Blog
    fields = ['title', 'content']
    template_name = 'KBA/blog_update_form.html'

    def form_valid(self, form):
        user = self.request.user
        form_blog = Blog.objects.get(pk=self.kwargs.get("pk"))

        if user == form_blog.blog_user:
            return super().form_valid(form)
        else:
            return HttpResponse("<h3>You don't have a permission</h3>")


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog-index')

    def form_valid(self, form):
        # 권한 검증
        user = self.request.user
        form_blog = Blog.objects.get(pk=self.kwargs.get("pk"))
        if user == form_blog.blog_user:
            return super().form_valid(form)
        else:
            return HttpResponse("<h3>You dont have a permission</h3>")


class BlogFormView(FormView):
    template_name = 'KBA/blog_comment.html'
    form_class = CommentForm

    def get_success_url(self):
        return reverse('blog-detail', kwargs={'pk': self.kwargs.get("pk")})

    def form_valid(self, form):
        form.instance.blog = Blog.objects.get(pk=self.kwargs.get("pk"))
        form.instance.comment_user = self.request.user
        form.save()
        return super().form_valid(form)



# def create





# class PlayerDetailView(DetailView):
#     model = Player
#     field = ['id', 'name', 'primary_position' ]

# class TeamDetailView(DetailView):
#
#     model = Team
#     slug_field = 'team'
#     field = ['name', 'year_formed', 'manager', 'players', 'content', 'no_titles']




# class AllModelList(ListView):
#     team = Team
#

#     p

    # model_detail.html is used since not declared with a 'template_name'

# Create your views here.

templates/KBA/about.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>about</h1>

{% endblock %}

templates/KBA/blog_comment.html
{% extends "base_generic.html" %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <fieldset>
            <legend class="mb-4 fw-bold">코멘트 쓰기</legend>
            {#            <div class="mb-3">#}
            {#                <label label for="id_comment_title" class="form-label fw-bold">TITLE</label>#}
            {#                <input class="form-control" type="text" name="comment_title" maxlength="200" required#}
            {#                       id="id_comment_title">#}
            {#            </div>#}

            <div class="mb-3">
                <label label for="id_comment_text" class="form-label fw-bold">CONTENT</label>
                <textarea class="form-control" type="text" name="comment_text" maxlength="200" required
                          id="id_comment_text"
                          style="height: 300px"></textarea>
            </div>

            <input class="btn btn-dark" type="submit" value="코멘트 작성">
        </fieldset>
    </form>
{% endblock content %}

templates/KBA/blog_confirm_delete.html
{% extends "base_generic.html" %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-2">
            <p class="fs-4">"{{ object }}" 해당 글을 삭제 합니다. </p>
        </div>

        <input class="btn btn-dark" type="submit" value="Confirm">
    </form>
{% endblock %}

templates/KBA/blog_detail.html
{% extends "base_generic.html" %}
{% block content %}


    <div class="card p-2 mb-3">
        <ul><p class="fs-4">{{ blog.title }}</p></ul>
        <ul>
            <small class="font-weight-bold text-primary">{{ blog.blog_user }}</small>
            <small class="font-weight-bold">{{ blog.updated|date:'Y-m-d H:i' }}</small>
        </ul>
    </div>
    <div class="card p-2 mb-4" style="height: 250px">
        <ul><p>{{ blog.content }}</p></ul>
    </div>
    <div>
        <a class="btn btn-dark mb-4" href="{% url 'blog-index' %}" role="button">뒤로가기</a>
        {% if user.is_authenticated %}
            <a class="btn btn-dark mb-4" href="{% url 'blog-form-comment' blog.id %}">코멘트</a>
            {% if blog.blog_user == request.user %}
                <a class="btn btn-dark mb-4" href="{% url 'blog-update' blog.id %}">업데이트</a>
                <a class="btn btn-dark mb-4" href="{% url 'blog-delete' blog.id %}">삭제</a>
            {% endif %}
        {% endif %}
    </div>
    {% if blog.comment_set.all %}
        <div>
            <p class="fs-3">Comments</p>
        </div>
        {% for c in blog.comment_set.all %}
            <div class="card p-3 mb-2">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="user d-flex flex-row align-items-center">
                        <span><small class="font-weight-bold text-primary">{{ c.comment_user }}</small> <small
                                class="font-weight-bold"> {{ c.comment_text }}</small></span></div>
                    <small>{{ c.comment_updated|date:'Y-m-d H:i' }} </small>
                </div>
                {#                <div class="action d-flex justify-content-between mt-2 align-items-center">#}
                {#                    <div class="reply px-4"><small>Remove</small> <span class="dots"></span> <small>Reply</small> <span#}
                {#                            class="dots"></span> <small>Translate</small></div>#}
                {#                    <div class="icons align-items-center"><i class="fa fa-star text-warning"></i> <i#}
                {#                            class="fa fa-check-circle-o check-icon"></i></div>#}
                {#                </div>#}
            </div>
        {% endfor %}
    {% endif %}


{% endblock content %}

templates/KBA/blog_form.html
# templates/KBA/blog_form.html

{% extends "base_generic.html" %}
<div>
    <form method="POST">
        {% csrf_token %}
        <fieldset>
            <legend>Blog</legend>
            {{ form }}
        </fieldset>
        <div>
            <button type="submit">Post</button>
        </div>
    </form>
</div>

templates/KBA/blog_list.html
{% extends "base_generic.html" %}

{% block content %}
    {% if object_list %}

        <table class="table table-hover mb-4">
        <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">ID</th>
            <th scope="col">Post Date</th>
        </tr>
        </thead>
        <tbody>

        {% for blog in object_list %}
            <tr>
                <td><a class="text-muted text-decoration-none"
                       href="{% url 'blog-detail' blog.id %}">{{ blog.title }}</a></td>
                <td class="text-decoration-none">{{ blog.blog_user }}</td>
                <td class="text-decoration-none">{{ blog.updated|date:'Y-m-d H:i' }}</td>
            </tr>
        {% endfor %}
    {% else %}
        <p>There's no blog content</p>
    {% endif %}

</tbody>
</table>
    <div class="d-grid gap-2 d-md-flex mb-4">
        <a class="btn btn-dark me-md-2" href="{% url 'blog-create' %}" role="button">글쓰기</a>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-1">
                <ul class="pagination">
                    <li class="page-item">
                        {% if page_obj.has_previous %}
                            <a class="page-link text-muted" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        {% endif %}

                        {% for page in paginator.page_range %}
                            <li class="page-item"><a class="page-link text-muted"
                                                     href="?page={{ page }}">{{ page }}</a></li>
                        {% endfor %}

                    {% if page_obj.has_next %}
                        <a class="page-link text-muted" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>

{% endblock %}

templates/KBA/blog_update_form.html
{% extends "base_generic.html" %}
{% block content %}
    <div class="mb-3">
        <form method="POST" >
            {% csrf_token %}
            <fieldset>
                <legend class="mb-4 fw-bold">글쓰기</legend>
                <div class="mb-3">
                    <label label for="id_title" class="form-label fw-bold">TITLE</label>
                    <input class="form-control mb-4" type="text" name="title" maxlength="200" required id="id_title" placeholder="Please enter your details."
                           value="{{ form.title.value }}" >

                </div>

                <div class="mb-3">
                    <label label for="id_content" class="form-label fw-bold">CONTENT</label>

                     <textarea rows=5 type="text" class="form-control mb-4" name="content"
                        placeholder="Please enter your details." required_id="id_text" style="height: 300px">{{ form.content.value }}</textarea>
                </div>

            </fieldset>
            <div>
                <button class="btn btn-dark" type="submit">글쓰기</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/KBA/detail.html
<h1>{{ team.name }}</h1>
    <textarea>{{ team.content }}</textarea>

<p>Manager: {{ team.manager}}</p>
<p>Year Formed: {{ team.year_formed}}</p>

<body>
{% if players %}
       <h3>Player Roster</h3>
    <ol start=1>
        {% for player in players %}
        <li>{{ player.name }} {{ player.primary_position }} </li>
        {% endfor %}
    </ol>
{% endif %}
{#{{ team.players_set.all}}#}


</body>

templates/KBA/home.html
{% extends "base_generic.html" %}

{%  block content %}

<h1>Home Template</h1>


<div>
    <div>
        {% for team in teams %}
            <div>
                <h5><a href="{% url 'team-list' %}" > {{ team.name }}</a> </h5>
            </div>

        {%  endfor %}


    </div>

</div>




{% endblock content %}

templates/KBA/player_detail.html
<h1>{{ player.name }}</h1>

{#<body>#}
{##}
{#{{ player.primary_position }}#}
{#{% if players %}#}
{#       <h3>Player Roster</h3>#}
{#    <ol start=1>#}
{#        {% for player in players %}#}
{#        <li>{{ player.name }} {{ player.primary_position }} </li>#}
{#        {% endfor %}#}
{#    </ol>#}
{#{% endif %}#}
{#{{ team.players_set.all}}#}
{##}
{##}
{#</body>#}

templates/KBA/player_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/KBA/team_detail.html
{% extends "base_generic.html" %}

<h1>{{ team.name }}</h1>
    <textarea>{{ team.content }}</textarea>

<p>Manager: {{ team.manager}}</p>
<p>Year Formed: {{ team.year_formed}}</p>

<body>
{% if players %}
       <h3>Player Roster</h3>
    <ol start=1>
        {% for player in players %}
        <li><a href="{% url 'player-detail' player.uuid %}">{{ player.name }}</a> {{ player.primary_position }} </li>
        {% endfor %}
    </ol>
{% endif %}
{#{{ team.players_set.all}}#}




</body>

templates/KBA/team_form.html
{% extends "base_generic.html" %}


{% block content %}


<div>
    <form method = "POST" action="">
         {% crsf_token %}

         <input type = "submit" value="Submit" />
    </form>

</div>


{% endblock content %}

templates/KBA/teams.html
# templates/KBA/teams.html
{% extends "base_generic.html" %}
{% block content %}
    {% if teams %}
        <ul>
            {% for team in teams %}
                <li><a href="./{{ team.name }}">{{ team.name }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There's no team content</p>
    {% endif %}

{% endblock %}